# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3307:3306"  # Puerto externo a 3307
    environment:
      MYSQL_ROOT_PASSWORD: example