# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    container_name: sales-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3307:3306"  # Puerto externo a 3307
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf 
      
  #   data-lake:
  #     image: docker.io/bitnami/minio:2024
  #     container_name: sales-datalake
  #     ports:
  #       - '9000:9000'
  #       - '9001:9001'
  #     volumes:
  #       - 'minio_data:/bitnami/minio/data'
  #     environment:
  #       - MINIO_ROOT_USER=minio-root-user
  #       - MINIO_ROOT_PASSWORD=minio-root-password

  #   portainer:
  #     image: portainer/portainer-ce:latest
  #     container_name: sales-portainer
  #     restart: always
  #     ports:
  #       - "9002:9000"
  #     environment:
  #       - ADMIN_PASSWORD=hashgenerado #User is admin
  #     volumes:
  #       - /var/run/docker.sock:/var/run/docker.sock
  #       - portainer_data:/data

  #   #https://bitnami.com/stack/apache-airflow/containers
  #   #https://github.com/bitnami/containers/blob/main/bitnami/airflow/docker-compose.yml
  #   postgresql:
  #     image: docker.io/bitnami/postgresql:latest
  #     volumes:
  #       - postgresql_data:/bitnami/postgresql
  #     environment:
  #       - POSTGRESQL_DATABASE=bitnami_airflow
  #       - POSTGRESQL_USERNAME=bn_airflow
  #       - POSTGRESQL_PASSWORD=bitnami1
  #       - ALLOW_EMPTY_PASSWORD=yes

  #   redis:
  #     image: docker.io/bitnami/redis:latest
  #     volumes:
  #       - redis_data:/bitnami
  #     environment:
  #       - ALLOW_EMPTY_PASSWORD=yes

  #   airflow-scheduler:
  #       image: docker.io/bitnami/airflow:2
  #       environment:
  #         - AIRFLOW_COMPONENT_TYPE=scheduler
  #         - AIRFLOW_DATABASE_NAME=bitnami_airflow
  #         - AIRFLOW_DATABASE_USERNAME=bn_airflow
  #         - AIRFLOW_DATABASE_PASSWORD=bitnami1
  #         - AIRFLOW_EXECUTOR=CeleryExecutor
  #         - AIRFLOW_WEBSERVER_HOST=airflow

  #   airflow-worker:
  #       image: docker.io/bitnami/airflow:2
  #       environment:
  #         - AIRFLOW_COMPONENT_TYPE=worker
  #         - AIRFLOW_DATABASE_NAME=bitnami_airflow
  #         - AIRFLOW_DATABASE_USERNAME=bn_airflow
  #         - AIRFLOW_DATABASE_PASSWORD=bitnami1
  #         - AIRFLOW_EXECUTOR=CeleryExecutor
  #         - AIRFLOW_WEBSERVER_HOST=airflow

  #   airflow:
  #     #User:user - pass: bitnami
  #     image: docker.io/bitnami/airflow:2
  #     environment:
  #       - AIRFLOW_DATABASE_NAME=bitnami_airflow
  #       - AIRFLOW_DATABASE_USERNAME=bn_airflow
  #       - AIRFLOW_DATABASE_PASSWORD=bitnami1
  #       - AIRFLOW_EXECUTOR=CeleryExecutor
  #     ports:
  #       - '8080:8080'

  # volumes:
  #   minio_data:
  #     driver: local
  #   portainer_data:
  #     driver: local
  #   postgresql_data:
  #     driver: local
  #   redis_data:
  #     driver: local