version: '3.1'

services:
  mysql-db:
    image: mysql
    container_name: sales-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3307:3306"
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf 